# Generated by Django 5.1.6 on 2025-03-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Adopted', 'Adopted')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
