# Generated by Django 5.1.6 on 2025-02-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_pets', '0001_initial'),
    ]

    operations = [
    ]
