# Generated by Django 5.1.6 on 2025-03-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pets', '0002_pet_adoption_status_pet_image_pet_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_pets.sellerprofile'),
        ),
    ]
