# Generated by Django 5.1.7 on 2025-03-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pets', '0003_alter_pet_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_pets.sellerprofile'),
        ),
    ]
