# Generated by Django 5.1.7 on 2025-03-08 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pets', '0004_alter_pet_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='interested_buyers',
            field=models.ManyToManyField(blank=True, related_name='interested_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
