# Generated by Django 5.1.7 on 2025-03-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pets', '0005_pet_interested_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
