# Generated by Django 5.1.6 on 2025-03-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pets', '0007_contactmessage_alter_buyerprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(max_length=50),
        ),
    ]
